from typing import Any, List, Mapping, Optional

def configure_starlark(
    *,
    allow_set: Optional[bool] = ...,
    allow_global_reassign: Optional[bool] = ...,
    allow_recursion: Optional[bool] = ...,
) -> None: ...

class Starlark(Mapping[str, Any]):
    def __init__(self) -> None: ...
    def eval(
        self, expr: str, *, filename: Optional[str] = ..., convert: Optional[bool] = ...
    ) -> Any: ...
    def exec(self, defs: str, *, filename: Optional[str] = ...) -> None: ...
    def keys(self) -> List[str]: ...
