from typing import Optional

class Starlark:
    def __init__(self) -> None: ...
    def eval(
        self, expr: str, filename: Optional[str] = ..., convert: Optional[bool] = ...
    ) -> str: ...
    def exec(self, defs: str, filename: Optional[str] = ...) -> None: ...
