class Starlark:
    def __init__(self) -> None: ...
    def eval(self, statement: str) -> str: ...
    def exec(self, data: str) -> None: ...

class StarlarkError(BaseException): ...
class SyntaxError(StarlarkError): ...
class EvalError(StarlarkError): ...
class UnexpectedError(StarlarkError): ...
