class Starlark:
    def __init__(self) -> None: ...
    def eval(self, statement: str) -> str: ...
    def exec(self, data: str) -> None: ...

class StarlarkError(BaseException):
    @property
    def message(self) -> str: ...

class SyntaxError(StarlarkError):
    @property
    def filename(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...

class EvalError(StarlarkError): ...
class UnexpectedError(StarlarkError): ...
