class Starlark:
    def __init__(self) -> None: ...
    def eval(self, statement: str) -> str: ...
    def exec(self, data: str) -> None: ...

class StarlarkError(BaseException):
    def __init__(self, error: str, error_type: str, /) -> None: ...
    @property
    def error(self) -> str: ...
    @property
    def error_type(self) -> str: ...

class SyntaxError(StarlarkError):
    def __init__(
        self,
        error: str,
        error_type: str,
        msg: str,
        filename: str,
        line: int,
        column: int,
        /,
    ) -> None: ...
    @property
    def msg(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...

class EvalError(StarlarkError):
    def __init__(self, error: str, error_type: str, backtrace: str, /) -> None: ...
    @property
    def backtrace(self) -> str: ...
