name: Devcontainer

on:
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the devcontainer
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1
        persist-credentials: false

    - name: Check .devcontainer changes
      id: changes
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      with:
        filters: |
          devcontainer:
            - '.devcontainer/**'

    - name: Devcontainer Build
      if: steps.changes.outputs.devcontainer == 'true'
      uses: devcontainers/ci@19ddf8c5778961129f90613da69436820ba5e0d9 # v0.3.1900000448
      with:
        # This is just to test the build when the files change.
        push: never
        imageName: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/devcontainer
        runCmd: echo done