name: Valgrind

on:
  workflow_dispatch:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest

    name: Valgrind
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install valgrind
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install valgrind

      - name: Run valgrind
        run: ./scripts/pytest-valgrind.sh
